# Generated by Django 3.0.3 on 2020-04-10 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('favorites', models.TextField()),

            ],
        ),
    ]
