# Generated by Django 3.0.3 on 2020-04-10 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userManager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='simpleuser',
            name='access_token',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='simpleuser',
            name='access_token_secret',
            field=models.TextField(default=''),
        ),
    ]
